import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AnnouncementBanner from "@/components/custom/announcement-banner";
import Navbar from "@/components/custom/navbar";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={<div className="h-12 bg-[#252F34]" />}>
          <AnnouncementBanner />
        </Suspense>
        <Suspense fallback={<div className="h-16 border-b bg-white" />}>
          <Navbar />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
